openppl-public/ppl.nn

src/ppl/nn/auxtools/to_graphviz.h

fixed graph viz node name bug.

fix graph viz node name

---

.gitignore
build.sh
cmake/deps.cmake
docs/en/building-from-source.md
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/resize2d/resize2d_fp32.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/roialign/roialign_n16cx_fp32.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/roialign/roialign_n16cx_fp32_avx.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/roialign/roialign_n16cx_fp32_avx512.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/roialign/roialign_ndarray_fp32.cpp
src/ppl/nn/oputils/onnx/reshape_pooling.cc
tests/models/op_info_manager_test.cc

Some C++ 17 feature not supported in MacOS clang (Darwin), this PR contains some fix specify on Darwin.

Fix compile error on MacOS (Darwin)

---

docs/en/cpp-api-reference.md

Update dead links of cpp-api-reference doc

[DOCs] Update dead links of cpp-api-reference doc

---

docs/en/onnx-model-opset-convert-guide.md
tools/convert_onnx_opset_version.py

add convert onnx opset version tool.

add convert onnx opset version tool

---

docs/en/onnx-model-opset-convert-guide.md

add a description about one opset convert bug about intializer with same name & how to fixed it.

update onnx model opset convert guide

---

src/ppl/nn/engines/cuda/buffered_cuda_allocator.cc
src/ppl/nn/engines/cuda/buffered_cuda_allocator.h

fix set device-id bug for non-default gpu

---

src/ppl/nn/engines/cuda/engine.cc
src/ppl/nn/engines/cuda/engine.h
src/ppl/nn/engines/cuda/optimizer/opt_graph.cc

改了configure的初始化的位置，现在跳过configure也可以正常执行了
静态图我在opt_graph里面判断了一下，如果对应维度上数据不是1 就不改了 (我看代码里1是动态图默认值，不是1说明这一维不是动态的)。

still run ok when skip cuda engine configure

---

docs/en/supported-ops-and-platforms.md

Update detailed support information

liyangjie Update supported-ops-and-platforms.md

---

src/ppl/nn/engines/x86/optimizer/ops/ppl/channel_shuffle_op.cc
src/ppl/nn/engines/x86/optimizer/opt_graph.cc
src/ppl/nn/engines/x86/optimizer/opt_graph.h

fix channelshuffle param init bug

fix channelshuffle param init bug

---

README.md
docs/en/supported-ops-and-platforms.md

modified support information

---

src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/conv2d_fp32_common.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/depthwise/avx512/conv2d_n16cx_depthwise_fp32_avx512.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/depthwise/sse/conv2d_n8cx_depthwise_blk1x1_kernel_fp32_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/depthwise/sse/conv2d_n8cx_depthwise_blk1x7_kernel_fp32_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/depthwise/sse/conv2d_n8cx_depthwise_fp32_sse.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/depthwise/sse/conv2d_n8cx_depthwise_fp32_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/depthwise/sse/conv2d_n8cx_depthwise_kernel_fp32_sse.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/depthwise/sse/conv2d_n8cx_depthwise_kernel_fp32_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/sse/conv2d_n8cx_direct_ndarray_blk1x1_kernel_fp32_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/sse/conv2d_n8cx_direct_ndarray_blk1x3_kernel_fp32_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/sse/conv2d_n8cx_direct_ndarray_fp32_sse.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/sse/conv2d_n8cx_direct_ndarray_fp32_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/sse/conv2d_n8cx_direct_ndarray_kernel_fp32_sse.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/sse/conv2d_n8cx_direct_ndarray_kernel_fp32_sse.h
src/ppl/nn/engines/x86/impls/test/test_conv2d.cpp

- `conv2d_n8cx_depthwise_fp32_sse`
- `conv2d_n8cx_direct_ndarray_fp32_sse`

X86 SSE `conv2d depthwise` and `conv2d direct ndarray`

---

src/ppl/nn/engines/x86/kernels/onnx/clip_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/conv/conv2d_dynamic_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/convtranspose_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/gemm_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/identity_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/maxpool_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/non_max_suppression_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/pad_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/resize_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/slice_kernel.cc
src/ppl/nn/engines/x86/macros.h
src/ppl/nn/oputils/onnx/reshape_non_max_suppression.cc
src/ppl/nn/oputils/onnx/reshape_resize.cc
src/ppl/nn/oputils/onnx/reshape_slice.cc

Refine some input tensor validation code, always get tensor by position, and check whether they are nullptr

refine some check input code

---

src/ppl/nn/engines/x86/impls/CMakeLists.txt
src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/fp32/deform_conv2d.h
src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/fp32/gemm.h
src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/fp32/lstm.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/common/array_param_helper.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/common/avx_tools.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/common/math_fma.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/common/math_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/deform_conv2d/deform_conv2d_fp32_fma.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/deform_conv2d/deform_im2col2d_fp32.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/deform_conv2d/deform_im2col2d_fp32.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_fp32_fma.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/gemm_ref_fp32.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/lstm/lstm_fp32_fma.cpp
src/ppl/nn/engines/x86/impls/test/test_fc.cpp
src/ppl/nn/engines/x86/impls/test/test_gemm_v2.cpp
src/ppl/nn/engines/x86/kernels/mmcv/mmcv_modulated_deform_conv2d_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/lstm_kernel.cc
src/ppl/nn/engines/x86/optimizer/ops/ppl/shape_operation_op.cc
src/ppl/nn/engines/x86/optimizer/ops/ppl/shape_operation_op.h
src/ppl/nn/optimizers/fuse_shape_optimizer.cc

- fma blas form `gemm`,  move old `test_gemm.cpp` to `test_gemm_v2.cpp` and renew `test_gemm.cpp`
- `lstm` fma based on fma `gemm`
- `deform_conv2d` fma based on fma `gemm`
- `shape_operation` select input format optimize

[X86] `gemm` fma

---

samples/python/maskrcnn_onnx/run_maskrcnn_onnx.py

Change `input_ima_path` to `input_img_path` in this PR.

Fix typos and add blank between punctuations

---

src/ppl/nn/engines/cuda/impls/include/cudakernel/common/macro.h
src/ppl/nn/engines/cuda/impls/include/cudakernel/reduce/reduce_helper.h
src/ppl/nn/engines/cuda/impls/src/arithmetic/arithmetic.cu
src/ppl/nn/engines/cuda/impls/src/arithmetic/logical.cu
src/ppl/nn/engines/cuda/impls/src/arithmetic/relation.cu
src/ppl/nn/engines/cuda/impls/src/memory/expand.cu
src/ppl/nn/engines/cuda/impls/src/nn/conv/2spk/common/const_macros.h
src/ppl/nn/engines/cuda/impls/src/nn/conv/common/merge_split.cu
src/ppl/nn/engines/cuda/impls/src/nn/conv/common/merge_split.h
src/ppl/nn/engines/cuda/impls/src/nn/conv/idxn/common/const_macros.h
src/ppl/nn/engines/cuda/impls/src/reformat/reformat.cu
src/ppl/nn/engines/cuda/kernels/onnx/reduce_mean_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/reduce_min_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/reduce_prod_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/reduce_sum_kernel.cc
src/ppl/nn/engines/cuda/params/conv_extra_param.cc

[feature][cuda]windows compile

---

src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/winograd/avx512/conv2d_n16cx_winograd_t31_kernel_fp32_avx512.h

[x86][bugfix] fix `conv2d_n16cx_winograd_t31_kernel_fp32_avx512.h`

---

samples/cpp/engine/demo_engine_context.h
src/ppl/nn/engines/cuda/engine_context.cc
src/ppl/nn/engines/cuda/engine_context.h
src/ppl/nn/engines/engine_context.h
src/ppl/nn/engines/x86/engine_context.h
src/ppl/nn/engines/x86/runtime_x86_device.h
src/ppl/nn/engines/x86/x86_device.h
src/ppl/nn/models/onnx/runtime_builder_impl.cc
src/ppl/nn/optimizers/utils.cc
src/ppl/nn/runtime/runtime_graph_info.h
src/ppl/nn/runtime/runtime_impl.cc
src/ppl/nn/runtime/runtime_impl.h
src/ppl/nn/utils/buffered_cpu_allocator.cc
src/ppl/nn/utils/buffered_cpu_allocator.h
tests/engines/tmp_engine_context.h
tests/optimizers/utils_test.cc

Syscalls may allocate consecutive virtual addresses, which can reduce memory usage in CompactBufferManager.

[opt][x86] use syscall to replace malloc/free.

---

src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/fma/conv2d_n16cx_direct_ndarray_fp32_fma.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/fma/conv2d_n16cx_direct_ndarray_fp32_fma.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/im2col_gemm/sse/conv2d_im2col_gemm_fp32_sse.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/deform_conv2d/deform_im2col2d_fp32.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/pd_conv2d/fma/pd_conv2d_n16cx_depthwise_kernel_fp32_fma.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/pd_conv2d/fma/pd_conv2d_n16cx_direct_ndarray_fp32_fma.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/pd_conv2d/fma/pd_conv2d_n16cx_direct_ndarray_fp32_fma.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/pd_conv2d/pd_conv2d_fp32_common.cpp
src/ppl/nn/engines/x86/impls/test/test_pd_conv2d.cpp

- PostDepthwiseConv2d: `direct_ndarray`
- `conv2d_im2col_gemm_fp32_sse` bug fix

PostDepthwiseConv2d: `direct_ndarray` & bug fix

---

src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/fp32/gather_nd.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/avx512/conv2d_n16cx_direct_ndarray_blk1x14_kernel_fp32_avx512.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/avx512/conv2d_n16cx_direct_ndarray_blk1x1_kernel_fp32_avx512.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/avx512/conv2d_n16cx_direct_ndarray_fp32_avx512.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/avx512/conv2d_n16cx_direct_ndarray_fp32_avx512.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/avx512/conv2d_n16cx_direct_ndarray_kernel_fp32_avx512.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/avx512/conv2d_n16cx_direct_ndarray_kernel_fp32_avx512.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/fma/conv2d_n16cx_direct_ndarray_fp32_fma.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/direct_ndarray/fma/conv2d_n16cx_direct_ndarray_kernel_fp32_fma.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/gemm_direct/avx512/conv2d_n16cx_gemm_direct_blk1x14_kernel_fp32_avx512.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gather_nd/gather_nd_fp32.cpp
src/ppl/nn/engines/x86/kernels/onnx/gather_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/gather_nd_kernel.cc

- refactor `conv2d_n16cx_direct_ndarray_fp32_avx512` with performance improvement
- fix `gather` and `gather_nd`

Refactor `conv2d_n16cx_direct_ndarray_fp32_avx512`

---

src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/arithmetic/sse/arithmetic_broadcast_n16cx_fp32_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/arithmetic/sse/arithmetic_broadcast_ndarray_fp32_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/int64/arithmetic/arithmetic_broadcast_n16cx_int64.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/int64/arithmetic/arithmetic_broadcast_ndarray_int64.h
src/ppl/nn/engines/x86/optimizer/opt_kernel_creator_manager.cc
src/ppl/nn/models/onnx/param_parser_manager.cc

- fix arithmetic multi-thread task distribution
- wider MaxPool opset support

fix arithmetic multi-thread task distribution

---

samples/cpp/run_model/classification.cpp

register Ops before create engine

[fix]fix cpp sample

---

src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/common/math_avx512.h

https://github.com/openppl-public/ppl.nn/issues/328
https://github.com/Tencent/ncnn/pull/3581/commits/35c231abc1af2bec147e07280adf58b72bb0b322

fix build with vs2017

---

src/ppl/nn/engines/cuda/impls/src/nn/global_pooling_ave.cu

3: opt global ave pooling for seresnet

[cuda][opt]: global pooling for seresnet

---

src/ppl/nn/engines/cuda/impls/include/cudakernel/nn/instance_normalization.h
src/ppl/nn/engines/cuda/impls/src/nn/instance_normalization.cu
src/ppl/nn/engines/cuda/kernels/onnx/instance_normalization_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/instance_normalization_kernel.h
src/ppl/nn/engines/cuda/optimizer/algos/algo_gemm.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_normal.h
src/ppl/nn/engines/cuda/optimizer/cuda_ops.cc
src/ppl/nn/engines/cuda/optimizer/fusions/fs_filter_manager.cc
src/ppl/nn/engines/cuda/optimizer/fusions/fs_filter_manager.h
src/ppl/nn/engines/cuda/optimizer/fusions/fs_instance_normalization.cc
src/ppl/nn/engines/cuda/optimizer/fusions/fs_instance_normalization.h
src/ppl/nn/engines/cuda/optimizer/ops/onnx/instance_normalization_op.cc
src/ppl/nn/engines/cuda/optimizer/ops/onnx/instance_normalization_op.h
src/ppl/nn/engines/cuda/params/instance_normalization_extra_param.h
src/ppl/nn/models/onnx/param_parser_manager.cc
src/ppl/nn/models/onnx/parsers/onnx/parse_instancenormalization_param.cc
src/ppl/nn/models/onnx/parsers/onnx/parse_instancenormalization_param.h
src/ppl/nn/models/pmx/generated/onnx_op_generated.h
src/ppl/nn/models/pmx/oputils/onnx/instance_normalization.cc
src/ppl/nn/models/pmx/oputils/onnx/instance_normalization.h
src/ppl/nn/models/pmx/schema/onnx_op.fbs
src/ppl/nn/oputils/onnx/reshape_instance_normalization.cc
src/ppl/nn/oputils/onnx/reshape_instance_normalization.h
src/ppl/nn/params/onnx/instance_normalization_param.h

add cuda instancenorm, related to issue #402

Cuda instancenorm

---

src/ppl/nn/engines/arm/impls/CMakeLists.txt
src/ppl/nn/engines/arm/optimizer/opt_graph.cc
src/ppl/nn/engines/arm/optimizer/opt_rule.h
src/ppl/nn/engines/arm/optimizer/opt_rule_manager.cc
src/ppl/nn/engines/arm/optimizer/opt_rule_manager.h

add more custom op interface:  
* change arm impls cmake
* add arm opt_graph rule register interface
* add arm before init optimize

[feature][arm server] add more custom op interface

---

src/ppl/nn/engines/cuda/impls/src/arithmetic/arithmetic.cu
src/ppl/nn/engines/cuda/impls/src/nn/softmax.cu
src/ppl/nn/engines/cuda/optimizer/fusions/fs_concat.cc

1. softmax bug when using reduce kernel
2. concat fusion judgement bug
3. mul broadcast bug on one-dimension broadcasting

Cuda softmax，concat fusion, Mul broadcasting bug

---

src/ppl/nn/engines/cuda/impls/include/cudakernel/unary/unary.h
src/ppl/nn/engines/cuda/impls/src/nn/pooling_max.cu
src/ppl/nn/engines/cuda/impls/src/unary/unary.cu
src/ppl/nn/engines/cuda/kernels/onnx/abs_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/abs_kernel.h
src/ppl/nn/engines/cuda/kernels/onnx/round_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/round_kernel.h
src/ppl/nn/engines/cuda/optimizer/cuda_ops.cc
src/ppl/nn/engines/cuda/optimizer/ops/onnx/abs_op.cc
src/ppl/nn/engines/cuda/optimizer/ops/onnx/abs_op.h
src/ppl/nn/engines/cuda/optimizer/ops/onnx/convtranspose_op.cc
src/ppl/nn/engines/cuda/optimizer/ops/onnx/round_op.cc
src/ppl/nn/engines/cuda/optimizer/ops/onnx/round_op.h
src/ppl/nn/engines/cuda/params/convtranspose_extra_param.h
src/ppl/nn/models/onnx/param_parser_manager.cc

1. add cuda abs&round
2. fix pooling f2s2 bug and convtranspose reshape bug

Cuda unary

---

src/ppl/nn/engines/cuda/impls/include/cudakernel/reformat/reformat.h
src/ppl/nn/engines/cuda/impls/src/reformat/cvt_format_type.cu
src/ppl/nn/engines/cuda/impls/src/reformat/cvt_type_per_elems.cuh
src/ppl/nn/engines/cuda/impls/src/reformat/reformat.cu

opt reformat when cvt format and type simultaneously needed

[cuda][opt]: fuse cvt format&type into one kernel

---

src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/fp32/gemm.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/abs/abs_fp32_sse.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/avx512/gemm_fp32_avx512.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/common/gemm_base_operation_fp32_avx.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/common/gemm_base_operation_fp32_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_fp32_fma.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/fma/gemm_kernel_fp32_fma.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/gemm_fp32.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/sse/gemm_fp32_sse.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/sse/gemm_kernel_fp32_sse.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/sse/gemm_kernel_fp32_sse.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gemm/sse/gemv_fp32_sse.cpp
src/ppl/nn/engines/x86/impls/test/test_gemm.cpp

- add new flagship sse gemm
- fix abs
- fix gemm avx512/fma when K == 0
- fix gemm avx512/fma prepack b function

[x86][feature][fix] new: flagship gemm_sse, fix: abs gemm_avx512/fma

---

src/ppl/nn/engines/arm/impls/include/ppl/kernel/arm_server/tanh/neon/tanh.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/common/math_neon.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/common/type_traits.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/tanh/neon/tanh.cpp
src/ppl/nn/engines/arm/kernels/onnx/tanh_kernel.cc
src/ppl/nn/engines/arm/kernels/onnx/tanh_kernel.h
src/ppl/nn/engines/arm/optimizer/arm_ops.cc
src/ppl/nn/engines/arm/optimizer/ops/onnx/tanh_op.cc
src/ppl/nn/engines/arm/optimizer/ops/onnx/tanh_op.h

[feature][arm server] add tanh op

---

src/ppl/nn/engines/cuda/impls/src/reformat/cvt_format_type.cu
src/ppl/nn/engines/cuda/impls/src/reformat/cvt_type_per_elems.cuh
src/ppl/nn/engines/cuda/impls/src/reformat/reformat.cu

per-channel reformat fix on cuda-int8 models

[cuda][fix]: reformat fix on per-channel mode

---

src/ppl/nn/engines/arm/impls/include/ppl/kernel/arm_server/hard_sigmoid/neon/hard_sigmoid.h
src/ppl/nn/engines/arm/impls/include/ppl/kernel/arm_server/hard_swish/neon/hard_swish.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/hard_sigmoid/neon/hard_sigmoid.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/hard_swish/neon/hard_swish.cpp
src/ppl/nn/engines/arm/kernels/onnx/hard_sigmoid_kernel.cc
src/ppl/nn/engines/arm/kernels/onnx/hard_sigmoid_kernel.h
src/ppl/nn/engines/arm/kernels/onnx/hard_swish_kernel.cc
src/ppl/nn/engines/arm/kernels/onnx/hard_swish_kernel.h
src/ppl/nn/engines/arm/optimizer/arm_ops.cc
src/ppl/nn/engines/arm/optimizer/ops/onnx/hard_sigmoid_op.cc
src/ppl/nn/engines/arm/optimizer/ops/onnx/hard_sigmoid_op.h
src/ppl/nn/engines/arm/optimizer/ops/onnx/hard_swish_op.cc
src/ppl/nn/engines/arm/optimizer/ops/onnx/hard_swish_op.h
src/ppl/nn/models/onnx/param_parser_manager.cc
src/ppl/nn/models/onnx/parsers/onnx/parse_hard_sigmoid_param.cc
src/ppl/nn/models/onnx/parsers/onnx/parse_hard_sigmoid_param.h
src/ppl/nn/params/onnx/hard_sigmoid_param.h

add HardSigmoid & HardSwish op.

[feature][arm server] add HardSigmoid & HardSwish op

---

docs/cn/arm-doc/add_op.md
docs/cn/x86-doc/add_op.md
docs/en/shape_operation.md
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/concat/neon/concat.cpp
src/ppl/nn/engines/cuda/impls/src/nn/gemm_int8.cu
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/common/concat/concat_common.h
tools/simple_flags.cc

[fix] Fix some typos.

---

src/ppl/nn/engines/arm/impls/include/ppl/kernel/arm_server/channel_shuffle/neon/channel_shuffle.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/channel_shuffle/neon/channel_shuffle.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/channel_shuffle/neon/channel_shuffle_nbcx_common.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/channel_shuffle/neon/channel_shuffle_ndarray_common.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/channel_shuffle/neon/channel_shuffle_specializations.h
src/ppl/nn/engines/arm/kernels/pmx/channel_shuffle_kernel.cc

add arm server channel shuffle normal impls.

[feature][arm server] add channel shuffle normal

---

src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/maxpool/neon/maxpool_fp16.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/maxpool/neon/maxpool_fp32.cpp

Fix MaxPool f2s2p0 algorithm. This should pass the GoogleNet test cases in CI.

[arm][fix] fix maxpool f2s2p0 to pass googlenet ci

---

src/ppl/nn/engines/cuda/impls/include/cudakernel/memory/pad.h
src/ppl/nn/engines/cuda/impls/src/memory/pad.cu
src/ppl/nn/engines/cuda/impls/src/memory/slice.cu
src/ppl/nn/engines/cuda/kernels/onnx/pad_kernel.cc

1. specilized pad and slice kernel for h&w operation

[cuda][opt]: pad and slice when only h&w involved

---

src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/fp32/conv2d.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/conv2d_fp32.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/winograd/sse/conv2d_winograd_b6f3_fp32_sse.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/winograd/sse/conv2d_winograd_b6f3_fp32_sse.h
src/ppl/nn/engines/x86/impls/test/test_conv2d.cpp

[feature][x86] add winograd b6f3 sse support

[feature][x86] add winograd b6f3 sse support

---

src/ppl/nn/engines/arm/impls/include/ppl/kernel/arm_server/conv2d/neon/conv2d.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/conv2d_common.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/depthwise/conv2d_n8cx_depthwise_fp16.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/depthwise/conv2d_n8cx_depthwise_fp16.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/direct/conv2d_n8cx_direct_fp16.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/direct/conv2d_n8cx_direct_fp16.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/direct_ndarray/conv2d_direct_ndarray_fp16.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/direct_ndarray/conv2d_direct_ndarray_fp16.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/im2col/conv2d_n8cx_im2col_fp16.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/im2col/conv2d_n8cx_im2col_fp16.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/winograd/conv2d_wgb2f3_fp16.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/winograd/conv2d_wgb2f3_fp16.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/winograd/conv2d_wgb4f3_fp16.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp16/winograd/conv2d_wgb4f3_fp16.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/depthwise/conv2d_n4cx_depthwise_fp32.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/depthwise/conv2d_n4cx_depthwise_fp32.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/direct/conv2d_n4cx_direct_fp32.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/direct/conv2d_n4cx_direct_fp32.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/direct_ndarray/conv2d_direct_ndarray_fp32.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/direct_ndarray/conv2d_direct_ndarray_fp32.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/im2col/conv2d_n4cx_im2col_fp32.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/im2col/conv2d_n4cx_im2col_fp32.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/winograd/conv2d_wgb2f3_fp32.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/winograd/conv2d_wgb2f3_fp32.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/winograd/conv2d_wgb4f3_fp32.cpp
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/conv2d/neon/fp32/winograd/conv2d_wgb4f3_fp32.h
src/ppl/nn/engines/arm/optimizer/ops/onnx/conv_op.cc

- Add padding type for convolution parameters
- Add more activation fusion types
- Reduce memory allocation and free in Conv algorithm selector

[feature][arm] update convolution op interface and simplify algorithm selector

---

src/ppl/nn/engines/cuda/impls/src/arithmetic/arithmetic.cu

[cuda][fix]: nhwc8 div supported

---

src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/fp32/one_hot.h
src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/int64/one_hot.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/common/one_hot/one_hot_common.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/one_hot/one_hot_fp32.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/int64/one_hot/one_hot_int64.cpp
src/ppl/nn/engines/x86/kernels/onnx/one_hot_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/one_hot_kernel.h
src/ppl/nn/engines/x86/optimizer/ops/onnx/one_hot_op.cc
src/ppl/nn/engines/x86/optimizer/ops/onnx/one_hot_op.h
src/ppl/nn/engines/x86/optimizer/x86_ops.cc
src/ppl/nn/models/onnx/param_parser_manager.cc
src/ppl/nn/models/onnx/parsers/onnx/parse_one_hot_param.cc
src/ppl/nn/models/onnx/parsers/onnx/parse_one_hot_param.h
src/ppl/nn/oputils/onnx/reshape_one_hot.cc
src/ppl/nn/oputils/onnx/reshape_one_hot.h
src/ppl/nn/params/onnx/one_hot_param.h

[x86][feature] add onehot op

---

src/ppl/nn/engines/cuda/optimizer/algos/algo_convtranspose.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_convtranspose.h

add constraint on convtranpose's type and format

[cuda][mod]: add constraint on deconv type and format

---

src/ppl/nn/engines/cuda/buffered_cuda_device.cc
src/ppl/nn/engines/cuda/impls/src/nn/conv/conv_fp16.cu
src/ppl/nn/engines/cuda/impls/src/nn/conv/conv_int8.cu
src/ppl/nn/engines/cuda/impls/src/nn/gemm.cu
src/ppl/nn/engines/cuda/impls/src/nn/gemm_int8.cu

add cuda-check for conv initial kernels

[cuda][fix] add cuda-arch check for conv initial kernels

---

src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv2d/sse/conv2d_winograd_b6f3_fp32_sse.cpp

[x86][fix] fix error when fuse with sum @Alcanderian

[x86][fix] fix error when fuse with sum

---

src/ppl/nn/engines/cuda/impls/CMakeLists.txt
src/ppl/nn/engines/cuda/impls/src/nn/conv/2spk/gen_2spk_sm75_fp16_hmma1688_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/2spk/gen_2spk_sm75_int8_imma8816_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/2spk/gen_2spk_sm80_fp16_hmma16816_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/2spk/gen_2spk_sm80_fp16_hmma1688_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/2spk/gen_2spk_sm80_int8_imma16816_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/2spk/gen_2spk_sm80_int8_imma16832_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/2spk/gen_2spk_sm80_int8_imma8816_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/conv_int8.cu
src/ppl/nn/engines/cuda/impls/src/nn/conv/idxn/gen_idxn_sm75_fp16_hmma1688_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/idxn/gen_idxn_sm75_int8_imma8816_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/idxn/gen_idxn_sm80_fp16_hmma16816_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/idxn/gen_idxn_sm80_int8_imma16816_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/idxn/gen_idxn_sm80_int8_imma16832_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/swzl/gen_swzl_sm75_fp16_hmma1688_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/swzl/gen_swzl_sm75_int8_imma8816_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/swzl/gen_swzl_sm80_fp16_hmma16816_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/swzl/gen_swzl_sm80_fp16_hmma1688_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/swzl/gen_swzl_sm80_int8_imma16816_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/swzl/gen_swzl_sm80_int8_imma16832_kernel.py
src/ppl/nn/engines/cuda/impls/src/nn/conv/swzl/gen_swzl_sm80_int8_imma8816_kernel.py
src/ppl/nn/engines/cuda/optimizer/algos/algo_conv_hmma.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_conv_imma.cc

To reduce lib size by cutting some cuda kernels of conv&gemm

[cuda][mod]: enable cuda kernel cut as default

---

include/ppl/nn/engines/cuda/options.h
python/engines/cuda/py_engine.cc
python/engines/cuda/py_engine.h
src/ppl/nn/engines/cuda/engine.cc
src/ppl/nn/engines/cuda/engine.h
src/ppl/nn/engines/cuda/optimizer/algos/algo_conv_hmma.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_conv_imma.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_convtranspose.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_gemm.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_matmul.cc
src/ppl/nn/engines/cuda/optimizer/opt_graph.cc
src/ppl/nn/engines/cuda/optimizer/opt_kernel.h
src/ppl/nn/engines/cuda/params/conv_extra_param.cc
src/ppl/nn/engines/cuda/params/conv_extra_param.h
tools/pplnn.cc

* remove `ENGINE_CONF_IMPORT_ALGORITHMS` and `ENGINE_CONF_EXPORT_ALGORITHMS`
* add `ENGINE_CONF_SET_EXPORT_ALGORITHMS_HANDLER`

[refactor][cuda] import and export algorithm info

---

src/ppl/nn/params/onnx/pooling_param.h

some error occur when deserialize caffe pooling

[cuda][fix]: undefined value when serialization

---

src/ppl/nn/engines/cuda/impls/src/nn/bgemm.cu
src/ppl/nn/engines/cuda/impls/src/nn/convtranspose.cu
src/ppl/nn/engines/cuda/impls/src/nn/gemm.cu
src/ppl/nn/engines/cuda/impls/src/nn/gemm_int8.cu
src/ppl/nn/engines/cuda/kernels/onnx/conv_depthwise_kernel.h
src/ppl/nn/engines/cuda/kernels/onnx/conv_hmma_kernel.h
src/ppl/nn/engines/cuda/kernels/onnx/conv_imma_kernel.h
src/ppl/nn/engines/cuda/params/conv_extra_param.cc
src/ppl/nn/engines/cuda/params/conv_extra_param.h
src/ppl/nn/engines/cuda/pmx/generated/cuda_op_params_generated.h
src/ppl/nn/engines/cuda/pmx/schema/cuda_op_params.fbs
src/ppl/nn/engines/cuda/pmx/utils.h

Two fix:
1. serialization error when jit mode enabled
2. compilation error when cuda < 10.2 and gcc < 5.5

Cuda jit cuda9

---

src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/fp32/gru.h
src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/fp32/lstm.h
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gru/gru_fp32.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gru/gru_fp32_avx512.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/gru/gru_fp32_fma.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/lstm/lstm_fp32_avx512.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/lstm/lstm_fp32_fma.cpp
src/ppl/nn/engines/x86/kernels/onnx/gru_kernel.cc
src/ppl/nn/engines/x86/kernels/onnx/gru_kernel.h
src/ppl/nn/engines/x86/kernels/onnx/lstm_kernel.cc
src/ppl/nn/engines/x86/optimizer/ops/onnx/gru_op.cc
src/ppl/nn/engines/x86/optimizer/ops/onnx/gru_op.h
src/ppl/nn/engines/x86/optimizer/x86_ops.cc
src/ppl/nn/engines/x86/params/gru_param.h
src/ppl/nn/models/onnx/param_parser_manager.cc
src/ppl/nn/models/onnx/parsers/onnx/parse_gru_param.cc
src/ppl/nn/models/onnx/parsers/onnx/parse_gru_param.h
src/ppl/nn/oputils/onnx/reshape_gru.cc
src/ppl/nn/oputils/onnx/reshape_gru.h
src/ppl/nn/params/onnx/gru_param.h

- support avx512 for lstm op.
- add gru op in x86 engine.
- support avx512, fma and naive version.
- support packed weights for gemm.

[x86][feature] add gru op 

---

src/ppl/nn/engines/cuda/kernels/onnx/prelu_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/prelu_kernel.h
src/ppl/nn/engines/cuda/optimizer/algos/algo_filter_manager.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_filter_manager.h
src/ppl/nn/engines/cuda/optimizer/algos/algo_normal.h
src/ppl/nn/engines/cuda/optimizer/algos/algo_prelu.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_prelu.h
src/ppl/nn/engines/cuda/optimizer/cuda_ops.cc
src/ppl/nn/engines/cuda/optimizer/ops/onnx/prelu_op.cc
src/ppl/nn/engines/cuda/optimizer/ops/onnx/prelu_op.h

[cuda][add]: prelu with inherited formats

---

src/ppl/nn/engines/cuda/impls/include/cudakernel/nn/one_hot.h
src/ppl/nn/engines/cuda/impls/include/cudakernel/reduce/argmin.h
src/ppl/nn/engines/cuda/impls/src/reduce/argmin.cu
src/ppl/nn/engines/cuda/kernels/onnx/argmin_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/argmin_kernel.h
src/ppl/nn/engines/cuda/kernels/onnx/one_hot_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/one_hot_kernel.h
src/ppl/nn/engines/cuda/optimizer/ops/onnx/argmin_op.cc
src/ppl/nn/engines/cuda/optimizer/ops/onnx/argmin_op.h
src/ppl/nn/engines/cuda/optimizer/ops/onnx/one_hot_op.cc
src/ppl/nn/engines/cuda/optimizer/ops/onnx/one_hot_op.h
src/ppl/nn/models/onnx/param_parser_manager.cc
src/ppl/nn/models/onnx/parsers/onnx/parse_argmin_param.cc
src/ppl/nn/models/onnx/parsers/onnx/parse_argmin_param.h
src/ppl/nn/oputils/onnx/reshape_argmin.cc
src/ppl/nn/oputils/onnx/reshape_argmin.h
src/ppl/nn/params/onnx/argmin_param.h

- Add operator argmin according to the code of argmax
- The implementation of one-hot in cuda kernels need to finish.

[CUDA] Add operator argmin and part of one-hot

---

src/ppl/nn/engines/cuda/impls/src/arithmetic/arithmetic.cu
src/ppl/nn/engines/cuda/kernels/onnx/conv_hmma_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/convtranspose_kernel.cc
src/ppl/nn/engines/cuda/optimizer/ops/pmx/channel_shuffle_op.cc
src/ppl/nn/engines/cuda/optimizer/ops/pmx/reduce_op.cc
src/ppl/nn/engines/cuda/optimizer/ops/pmx/shape_operation_op.cc
src/ppl/nn/engines/cuda/optimizer/ops/pmx/shape_operation_op.h
src/ppl/nn/models/pmx/generated/pmx_op_generated.h
src/ppl/nn/models/pmx/oputils/pmx/channel_shuffle.h
src/ppl/nn/models/pmx/oputils/pmx/ppl_shape_operation.cc
src/ppl/nn/models/pmx/oputils/pmx/ppl_shape_operation.h
src/ppl/nn/models/pmx/schema/pmx_op.fbs
src/ppl/nn/params/pmx/shape_operation_param.h

1. add some op serialization
2. fix arithmetic and reduce
3. support dynamic weight

Cuda dynamic ops2

---

src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv_transpose/col2im_fp32_avx.cpp
src/ppl/nn/engines/x86/impls/src/ppl/kernel/x86/fp32/conv_transpose/col2im_fp32_sse.cpp

[x86][fix] fix `deconv` w_end bug

---

src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/common/math_neon.h
src/ppl/nn/engines/arm/impls/src/ppl/kernel/arm_server/common/type_traits.h

`vsetq_lane_f32` has return value

[arm][fix] vsetq_lane_f32 bug

---

src/ppl/nn/engines/cuda/impls/src/arithmetic/arithmetic.cu
src/ppl/nn/engines/cuda/impls/src/memory/pad.cu
src/ppl/nn/engines/cuda/impls/src/memory/subpixel.cu
src/ppl/nn/engines/cuda/impls/src/unary/clip.cu
src/ppl/nn/engines/cuda/impls/src/unary/unary_zero.cu
src/ppl/nn/engines/cuda/optimizer/algos/algo_conv_depthwise.cc

opt some cuda ops when test caffe networks

Cuda opt ops2

---

src/ppl/nn/engines/cuda/kernels/onnx/reshape_kernel.cc
src/ppl/nn/engines/cuda/optimizer/opt_kernel.h
src/ppl/nn/optimizers/graph_optimizer_manager.cc
src/ppl/nn/optimizers/identity_node_optimizer.cc
src/ppl/nn/optimizers/identity_node_optimizer.h

[feature] Add identity fuse then use it for reshape transbuffer determination.

[feature] Add identity fuse

---

src/ppl/nn/engines/cuda/impls/CMakeLists.txt

support assign specific arch to compile

[cuda][add]: support assign specific arch to compile

---

src/ppl/nn/engines/cuda/kernels/mmcv/mmcv_modulated_deform_conv2d_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/convtranspose_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/gemm_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/lstm_kernel.cc
src/ppl/nn/engines/cuda/kernels/onnx/matmul_kernel.cc

when jit is off, compile bug occurs because of cuda_module

[cuda][fix]: compile bug when jit mode is off

---

src/ppl/nn/engines/cuda/optimizer/algos/algo_convtranspose.cc

Fix v0.9.0 error on mmdeploy dbnet

[cuda][fix]: deconv error when in-c is not aligned

---

src/ppl/nn/engines/cuda/kernels/pmx/ms_deformable_attention_kernel.cc
src/ppl/nn/engines/cuda/kernels/pmx/ms_deformable_attention_kernel.h
src/ppl/nn/engines/cuda/optimizer/cuda_ops.cc
src/ppl/nn/engines/cuda/optimizer/ops/pmx/ms_deformable_attention_op.cc
src/ppl/nn/engines/cuda/optimizer/ops/pmx/ms_deformable_attention_op.h
src/ppl/nn/models/onnx/param_parser_manager.cc
src/ppl/nn/models/onnx/parsers/pmx/parse_ms_deformable_attention_param.cc
src/ppl/nn/models/onnx/parsers/pmx/parse_ms_deformable_attention_param.h
src/ppl/nn/oputils/onnx/reshape_ms_deformable_attention.cc
src/ppl/nn/oputils/onnx/reshape_ms_deformable_attention.h
src/ppl/nn/params/pmx/ms_deformable_attention_param.h

add MS deformable attention kernel

add msdeformatten kernel

---

src/ppl/nn/common/input_output_info.h
src/ppl/nn/engines/cuda/kernels/onnx/softmax_kernel.cc

[fix][cuda]softmax

---

src/ppl/nn/engines/cuda/optimizer/cuda_ops.cc
src/ppl/nn/engines/cuda/params/conv_extra_param.cc

[cuda][mod]: adaption for 1d-conv

---

src/ppl/nn/engines/cuda/optimizer/algos/algo_filter_manager.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_graph.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_graph.h

[cuda][add]: resize nhwc impls

---

include/ppl/nn/engines/cuda/options.h
python/engines/cuda/py_engine.cc
src/ppl/nn/engines/cuda/engine.cc
src/ppl/nn/engines/cuda/engine.h
src/ppl/nn/engines/cuda/optimizer/algos/algo_conv_hmma.cc
src/ppl/nn/engines/cuda/optimizer/algos/algo_filter_manager.h
src/ppl/nn/engines/cuda/optimizer/opt_graph.cc
src/ppl/nn/runtime/runtime_partition_info.h

Cuda add refit merge

---

src/ppl/nn/engines/cuda/optimizer/algos/algo_gemm.cc

[cuda][fix]: gemm error when tranB==0

---

python/engines/cuda/py_engine.cc
src/ppl/nn/engines/cuda/engine.cc
src/ppl/nn/engines/cuda/engine.h
src/ppl/nn/engines/cuda/optimizer/algos/algo_conv_hmma.cc
src/ppl/nn/engines/cuda/optimizer/opt_graph.cc
src/ppl/nn/engines/cuda/optimizer/opt_graph.h
src/ppl/nn/engines/cuda/optimizer/opt_kernel.h
src/ppl/nn/runtime/runtime_partition_info.h

Move Refit info into cuda part

Update: move refit_info to cuda & use ptr to update weights

---

include/ppl/nn/engines/cuda/options.h
src/ppl/nn/engines/cuda/engine.cc
src/ppl/nn/engines/cuda/engine.h

quick select flag for gemm solely

[cuda-add]: quick select gemm option

---

src/ppl/nn/optimizers/fuse_constant_optimizer.cc

support external weights file when fuse constant optimizer

[fix] support external weights file when fuse constant optimizer
